

package laberinto;

import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class visor extends javax.swing.JFrame implements Runnable{
public int min=0,seg=0;

Thread hilo;
    
    public visor() {
        initComponents();
        grupo.add(rentrada);
        grupo.add(rsalida);
        grupo.add(rmuro);  
        acerca.pack();
       
        this.setLocationRelativeTo(null);
        acerca.setLocationRelativeTo(null);
        hilo=new Thread(this);
       // this.add(lienzo1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acerca = new javax.swing.JFrame();
        grupo = new javax.swing.ButtonGroup();
        lienzo1 = new laberinto.lienzo();
        jPanel1 = new javax.swing.JPanel();
        rentrada = new javax.swing.JRadioButton();
        rmuro = new javax.swing.JRadioButton();
        rsalida = new javax.swing.JRadioButton();
        btnResolver = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout acercaLayout = new javax.swing.GroupLayout(acerca.getContentPane());
        acerca.getContentPane().setLayout(acercaLayout);
        acercaLayout.setHorizontalGroup(
            acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        acercaLayout.setVerticalGroup(
            acercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        rentrada.setText("Posicion Inicial");
        rentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentradaActionPerformed(evt);
            }
        });
        jPanel1.add(rentrada, java.awt.BorderLayout.CENTER);

        rmuro.setText("Fijar Obstaculo");
        rmuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmuroActionPerformed(evt);
            }
        });
        jPanel1.add(rmuro, java.awt.BorderLayout.PAGE_START);

        rsalida.setText("Posicion Final");
        rsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsalidaActionPerformed(evt);
            }
        });
        jPanel1.add(rsalida, java.awt.BorderLayout.PAGE_END);

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        btnReinicio.setText("Reiniciar");
        btnReinicio.setToolTipText("");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });

        btnRandom.setText("Random");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(432, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReinicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResolver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRandom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 189, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnResolver)
                .addGap(33, 33, 33)
                .addComponent(btnReinicio)
                .addGap(40, 40, 40)
                .addComponent(btnRandom)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
      
        try {
              
            lienzo1.hilo.start();
            btnResolver.setEnabled(false);
            lienzo1.f=2;
           // hilo.start();
         
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ocurrio un problema "+e.getMessage() );
        }
    }//GEN-LAST:event_btnResolverActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        lienzo1.hilo.stop();
        lienzo1.reinicio();
        btnResolver.setEnabled(true);
        hilo =new Thread(this);
        min=0;
        seg=0;
        //jLabel2.setText("min"+min+"  "+"seg"+seg);
    }//GEN-LAST:event_btnReinicioActionPerformed

    private void rmuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmuroActionPerformed
        if (rmuro.isSelected()) {
            lienzo1.radiobotones=3;
        }
    }//GEN-LAST:event_rmuroActionPerformed

    private void rsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsalidaActionPerformed
        if (rsalida.isSelected()) {
            lienzo1.radiobotones=2;
        }
    }//GEN-LAST:event_rsalidaActionPerformed

    private void rentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentradaActionPerformed
        if (rentrada.isSelected()) {
            lienzo1.radiobotones=1;
        }
    }//GEN-LAST:event_rentradaActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
      
           lienzo1.hilo.stop();
        lienzo1.Aleatorio();
        btnResolver.setEnabled(true);
        hilo =new Thread(this);
        min=0;
        seg=0;
        //jLabel2.setText("min"+min+"  "+"seg"+seg);
        
        
        
    }//GEN-LAST:event_btnRandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visor().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame acerca;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JButton btnResolver;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private laberinto.lienzo lienzo1;
    private javax.swing.JRadioButton rentrada;
    private javax.swing.JRadioButton rmuro;
    private javax.swing.JRadioButton rsalida;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {            
            try {
                Thread.sleep(1000);
                seg++;
                if(seg>59)
                {
                min++;
                seg=0;
                }
                
            //jLabel2.setText("min"+min+"  "+"seg"+seg);
                if (lienzo1.termino==1) {
                    hilo.stop();
                }
   
            } catch (Exception e) {
            }
        }
    }
}
